### ISSUE TITLE
Does chapter support work on everand?

### ISSUE THREAD

**Issue by Popkin2020** [jo1gi/audiobook-dl#107]
If I use audiobook-dl -c <cookie file> <url>, I get thousands of aac files.
If I use --combine then I get a single file without chapters, I also tried --output-format mp3/m4b, none of them has chapters.

**Comment by jo1gi** [comment]
Chapters should work with all sites.

**Comment by Popkin2020** [comment]
Still can't find out how to do it, I absolutely tried everything.

**Comment by jo1gi** [comment]
What's the output of `ffprobe`?

**Comment by Popkin2020** [comment]
What do you mean? Sorry I don't understand much about these. The file I get is just aac file

**Comment by jo1gi** [comment]
Run `ffprobe <path_to_file>`. That should about details about the file.
