### ISSUE TITLE
Possible support for yourcloudlibrary.com

### ISSUE THREAD

**Issue by Spectroxx** [jo1gi/audiobook-dl#11]
Would yourcloudlibrary.com be a service you would consider adding support for?

**Comment by jo1gi** [comment]
I would like to support it, but I don't have any way of logging in.

**Comment by Spectroxx** [comment]
Right, I suppose that's true. I'll check and see If I can figure something out.

**Comment by jo1gi** [comment]
Have you figured something out? I have a few ideas if you haven't:
- You could give me your password (I understand if you think that's a bad idea)
- I could help you develop it
- You could send me a HAR file of all requests made while listening in the browser
