### ISSUE TITLE
"The url you provided is not supported by audiobook-dl" when using a Libby url

### ISSUE THREAD

**Issue by memory-arg** [jo1gi/audiobook-dl#121]
**Installation method:**
Installed with pip

**Version:**
python 3.10.12 
audiobook-dl 0.7.3

**Describe the bug**
audiobook-dl fails to identify "libbyapp.com" as a supported platform

**Command output**

isaac@pop-os:~/Documents/Audiobooks$ audiobook-dl -c cookies-libbyapp-com.txt https://libbyapp.com/open/loan/77617053/9296630 -d
DEBUG audiobook-dl 0.7.3
DEBUG python 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
 INFO Finding compatible source
ERROR: The url you provided is not supported by audiobook-dl

Supported services are:
 • audiobooks.com
 • Blinkist
 • BookBeat
 • Chirp
 • eReolen
 • Everand
 • Libby
 • Librivox
 • Mofibo
 • Nextory
 • Overdrive
 • Podimo
 • Saxo
 • Scribd
 • Storytel
 • YourCloudLibrary

Traceback
Traceback (most recent call last):
  File "/home/isaac/.local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 31, in main
    process_url(url, options, config)
  File "/home/isaac/.local/lib/python3.10/site-packages/audiobookdl/__main__.py", line 49, in process_url
    source = find_compatible_source(url)
  File "/home/isaac/.local/lib/python3.10/site-packages/audiobookdl/sources/__init__.py", line 28, in find_compatible_source
    raise NoSourceFound
audiobookdl.exceptions.NoSourceFound

**Comment by memory-arg** [comment]
Coming back to this and actually looking at overdrive.py, there isn't any code to download from Libby, only Overdrive. I'm not sure why Libby is listed as a supported source.

**Comment by shameez-struggles-to-commit** [comment]
To confirm, there is no libby support?
