### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by jaan143** [jo1gi/audiobook-dl#3]
i installed everything and after that when i ran command i am getting this error

PS C:\Users\Vicky> audiobook-dl -c C:\Users\Vicky\Downloads\audiobook-dl-master\audiobook-dl-master\cookies.txt https://www.scribd.com/audiobook/514982249/Losing-weight-the-healthy-way-The-carb-cycling-How-to-get-results-without-giving-up-your-favorite-food
Finding compatible service
ERROR Could not find any mathing service

**Comment by jo1gi** [comment]
It currently only works with links to the page where you listen to the audiobook.

**Comment by jo1gi** [comment]
Added a line to the README to make it more obvious (commit 42bd022).

**Comment by jaan143** [comment]
now i am getting this issue it is not found any package call "mutagenpillowpydub"

PS C:\Users\Hp> audiobook-dl -c C:\cookies.txt https://www.scribd.com/listen/517606493
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\Scripts\audiobook-dl-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 3088, in <module>
    @_call_aside
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mutagenpillowpydub' distribution was not found and is required by audiobook-dl
PS C:\Users\Hp>

**Comment by jo1gi** [comment]
@jaan143 It looks like you are missing some dependencies. Try running `pip3 install mutagen pillow pydub`. That should install them for you.

**Comment by jaan143** [comment]
these all dependencies are installed

PS C:\Users\Hp> pip3 install mutagen pillow pydub
Requirement already satisfied: mutagen in c:\users\hp\appdata\local\programs\python\python36\lib\site-packages (1.45.1)
Requirement already satisfied: pillow in c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\pillow-8.3.1-py3.6-win-amd64.egg (8.3.1)
Requirement already satisfied: pydub in c:\users\hp\appdata\local\programs\python\python36\lib\site-packages (0.25.1)
PS C:\Users\Hp>

**Comment by jaan143** [comment]
Dear i think you write wrong spell (without spaces) thats why it is also cannot search here you can check

Processing dependencies for audiobook-dl==0.1.0
Searching for mutagenpillowpydub
Reading https://pypi.org/simple/mutagenpillowpydub/
Couldn't find index page for 'mutagenpillowpydub' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for mutagenpillowpydub
error: Could not find suitable distribution for Requirement.parse('mutagenpillowpydub')
PS C:\Users\Hp\Downloads\Compressed\audiobook-dl-master\audiobook-dl-master>

**Comment by jo1gi** [comment]
I can't find it anywhere in the program. Try downloading the newest version. It works for me.

**Comment by jaan143** [comment]
i am getting same issue in other laptop also
can you come in my pc through teamv ?

**Comment by jo1gi** [comment]
I can try

**Comment by jaan143** [comment]
ok give me please your email i will send you there teamv access

**Comment by jo1gi** [comment]
joakimholm@tutanota.com

**Comment by jaan143** [comment]
sent you email kindly check

**Comment by jo1gi** [comment]
I received it

**Comment by jaan143** [comment]
sent you details please connect it

**Comment by jaan143** [comment]
Dear add some text in script to replace title : with _ (underscore)
every book which title have ":" is getting error like this one you can see

NotADirectoryError: [WinError 267] The directory name is invalid: 'Tuesday: The Curse of the Blue Spots'

**Comment by jo1gi** [comment]
Sry. Didn't think about that. It's not a problem on linux. I will try to fix it as soon as possible.

**Comment by jaan143** [comment]
i got the issue why it is not combining 
actually script is also trying to combine jpg file which is not streaming file and then giving this error
" Output file #0 does not contain any stream "

this #0 file is jpg file and this is the reason got error in combine files. if you can skip this jpg file in combining then  it will work perfect

**Comment by jo1gi** [comment]
I think I fixed both problems.

**Comment by jaan143** [comment]
@jo1gi Dear  this is working perfect now
thank you very very much for update
