### ISSUE TITLE
Failed to combine audio files

### ISSUE THREAD

**Issue by adampalli** [jo1gi/audiobook-dl#32]
I tried downloading audiobooks from Scribd. It's getting downloaded without any issues. But when I try to combine them, I get the following error. 

ERROR: Failed to combine audio files

I'm in the latest version (v0.4.3). I have also installed the latest version of ffmpeg. I use a cookie file to download the audiobook. I have attached the screenshot for reference. 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/117727805/225916812-2d6547c1-c567-4cb9-bb94-c459fc2b3330.png">

**Comment by jo1gi** [comment]
@adampalli Could you send the output when using the `--debug`flag?

**Comment by adampalli** [comment]
> @adampalli Could you send the output when using the `--debug` flag?

Here it is

Downloading 18 files - Dark Psychology ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%
Converting files
Combining files
ffmpeg version 2023-03-05-git-912ac82a3c-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  6.100 / 60.  6.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
concat:Dark Psychology\Dark Psychology\Dark Psychology - Part 1.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 2.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 3.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 4.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 5.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 6.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 7.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 8.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 9.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 10.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 11.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 12.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 13.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 14.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 15.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 16.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 17.mp3|Dark Psychology\Dark Psychology\Dark Psychology - Part 18.mp3: No such file or directory
ERROR: Failed to combine audio files

**Comment by jo1gi** [comment]
I have added a new version. Hope it works.

**Comment by adampalli** [comment]
> I have added a new version. Hope it works.

It fixed the issue! Thanks for the swift update :)
