### ISSUE TITLE
audio missing

### ISSUE THREAD

**Issue by evafans** [jo1gi/audiobook-dl#5]
IN some audiobook the first chapter was missed，this happens randomly.the following is one of them.
https://www.scribd.com/listen/398022814
https://www.scribd.com/audiobook/398022814/The-Bostonians

**Comment by jo1gi** [comment]
I'm sorry I haven't replied earlier. I can't reproduce the problem. Have you tried downloading it again?

**Comment by evafans** [comment]
I tried the latest version, but the problem remains unsolved.
https://www.scribd.com/listen/237848637
There were supposed to be 48 mp3s, but only 47 mp3s were downloaded, chapter 1 was missing, during the process, I saw part 1 was downloaded twice, and the second one is actually chaper 2 and it replaced chapter 1.
I don't know whether you can reproduce the problem.

**Comment by jo1gi** [comment]
I tried to download the same audiobook. All 48 audio files were downloaded correctly. The first chapter (prologue) is stored in `The Alchemist - Part 000.mp3`.

**Comment by evafans** [comment]
There are only 47 audio files plus 1 cover image file here. I don't know what went wrong.

**Comment by jo1gi** [comment]
That's weird. Is it only those books you have problems with or is it all books?

**Comment by evafans** [comment]
I'm happy to you, in the latest version, this problem has been resolved on my computer.
