### ISSUE TITLE
BookBeat chapter 

### ISSUE THREAD

**Issue by maikachen** [jo1gi/audiobook-dl#55]
**Installation method:**
*Github repo or pip/pypi*
pip

**Version:**
*Python version and audiobook-dl version*
newest Version

**Describe the bug**
i Tried Bookbeats , it download it perfect, but it not make any chapters and it´s mp4 in the end

**Command output**
DEBUG audiobook-dl 0.6.2
DEBUG python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Finding compatible source
Authenticating with bookbeat
DEBUG Logging in

Downloading xxxxxxxxxxxxxxxxxx… from bookbeat
DEBUG Starting downloading file:
https://prod-bb-download.akamaized.net/api/download/mp4/xxxxxxxxxxxxxxxxx token=xxxxxxxxxxxxxxxxxxx
  Downloading Die Mutter – Mommy liebt dich über alles … ---------------------------------------- 100%
  Adding chapters
DEBUG Could not add chapters
  Adding metadata
  Embedding cover

any solution or did i make something wrong ?

**Comment by jo1gi** [comment]
Try running it with `--output-format mp3`. That should convert the files to mp3 and make it possible to add chapters. It requires ffmpeg to be installed.

**Comment by jo1gi** [comment]
Did it work?

**Comment by maikachen** [comment]
> 

oh yes thank you it worked
