### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by masteoo** [jo1gi/audiobook-dl#58]
Hello to all and sorry again to bother but I have this problem in downloading this audiobook series :(
It seems that I cannot download titles too long.. is like that? What can I do? 
I already downloaded other audiobooks smoothly but I cannot download this serie. 
I use Termux in no rooted Tab S8.
Thanks for your support (telegram @proseccodoc )

![Screenshot_20230927_112009_Telegram](https://github.com/jo1gi/audiobook-dl/assets/120033556/43db2d18-07e0-4874-90c1-71bfb4caeac6)

**Comment by akirataguchi115** [comment]
Could there be some limitations to book size in audiobook-dl?

**Comment by masteoo** [comment]
> Could there be some limitations to book size in audiobook-dl?

I don't think because I downloaded a 40h audiobook (1.04 giga) with no problem. This error audiobook is just 13h long but has a loooong Title

**Comment by jo1gi** [comment]
You can change the name with `-o <new-file-name>`.

**Comment by akirataguchi115** [comment]
Yeah try to check if changing the output name to something more simple.

The error message seems to come from here
https://github.com/jo1gi/audiobook-dl/blob/29b1856cc711c7b97846738c2f5e5b9fefaf9456/audiobookdl/output/download.py#L167-L173

So I'm betting that it really might have something to do with file name.

**Comment by masteoo** [comment]
> You can change the file name with `-o <new-file-name>`.

🔝🔝 thanks it worked:)
