### ISSUE TITLE
.cue file with chapters

### ISSUE THREAD

**Issue by nonab** [jo1gi/audiobook-dl#67]
I'm struggling to find a player for android that understands chapters embedded in mp3 file and came up with an idea.

Creating a cue file with chapters would be universal for this case i believe.

It's not a bug but enhancemt idea.

**Comment by jo1gi** [comment]
I use [Voice](https://github.com/PaulWoitaschek/Voice) and haven't had a problem with chapters.

**Comment by nonab** [comment]
Thanks for the tip. I'm closing it then.
