### ISSUE TITLE
scribd did not work for me 

### ISSUE THREAD

**Issue by thedkm** [jo1gi/audiobook-dl#7]
scribd did not work for me 

inding compatible source
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python36\Scripts\audiobook-dl-script.py", line 11, in <module>
    load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\__main__.py", line 54, in run
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 15, in download
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\sources\scribd.py", line 71, in before
TypeError: 'NoneType' object is not subscriptable

**Comment by jo1gi** [comment]
Which book did you try to download? I still haven't gotten Scribd originals to work. They work in a different way than the rest of the audiobooks.

**Comment by thedkm** [comment]
https://www.scribd.com/audiobook/397089311/Cry-Like-a-Man-Fighting-for-Freedom-from-Emotional-Incarceration
https://www.scribd.com/audiobook/315859440/It-Wasn-t-Your-Fault-Freeing-Yourself-from-the-Shame-of-Childhood-Abuse-with-the-Power-of-Self-Compassion

**Comment by jo1gi** [comment]
I just tried downloading the same books and I had no problems. Are you sure that you have provided valid cookies? It is required that you give the program a file containing cookies for it to be able to download from Scribd.

**Comment by thedkm** [comment]
will try again

**Comment by thedkm** [comment]
anyway good work i hope u can figure out downloading the Scribd originals  good luck.

**Comment by jo1gi** [comment]
Thanks.
Please tell me if you run into any other problems or have any ideas for improvements.

**Comment by thedkm** [comment]
hey are u on telegram?? I wanna discuss something about Scribd orignals

**Comment by thedkm** [comment]
ahh I see you already figured it out nice job does it working ???

**Comment by jo1gi** [comment]
It works but there are still some problems. The progress bar will go to 100% even though it is still downloading. It still works it is just a visual bug. It is also recommended to use the `--combine` argument since Scribd originals consists of a lot of files.

**Comment by jo1gi** [comment]
I just tested it with the `--combine` argument and it seems like it does not work right now.

**Comment by jo1gi** [comment]
It does not work on most Scribd Originals, but I have gotten it to work on a few.

**Comment by thedkm** [comment]
ohh sad I teste 1DM app to download it n it works u can look how it works.

**Comment by thedkm** [comment]
can u tell which one u managed to get it work and how??I wanna test too

**Comment by jo1gi** [comment]
I don't remember. I just chose a random book. I know why they don't work. The files are encrypted and I have to figure out how they can be decrypted to download them correctly.

**Comment by thedkm** [comment]
ahh 1DM does decryption idk how but it works

**Comment by jo1gi** [comment]
Are you sure it works on Scribd originals and not just normal audiobooks?

**Comment by thedkm** [comment]
yes I tested https://www.scribd.com/audiobook/469845574/The-Devil-and-Harper-Lee and U can try 1dm app on adroid.

**Comment by jo1gi** [comment]
I will take a look.

**Comment by thedkm** [comment]
1dm can download files n decrypt it sometimes it can give merge error but main part is already done

**Comment by jo1gi** [comment]
I think I have fixed the problem 6c57a3b.

**Comment by thedkm** [comment]
ohhh nice , will try it now

**Comment by thedkm** [comment]
not able to install Crypto'

**Comment by thedkm** [comment]
Combining files
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36\Scripts\audiobook-dl-script.py", line 33, in <module>
    sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\__main__.py", line 54, in run
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 37, in download
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 51, in combined_audiobook
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 62, in combine_files
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\utils\output.py", line 33, in combine_audiofiles
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

**Comment by thedkm** [comment]
One more suggestion for scribd ordinals file names The Devil and Harper Lee - Part 0 ,1 It should be like  The Devil and Harper Lee - Part 00,01, former will give problem in merging

**Comment by thedkm** [comment]
https://www.scribd.com/audiobook/543626939/Your-Work-from-Home-Life-Redefine-Reorganize-and-Reinvent-Your-Remote-Work-Tips-for-Building-a-Home-Based-Working-Career try this it gave weird warnings

**Comment by jo1gi** [comment]
> Combining files
> Traceback (most recent call last):
> File "C:\Users\AppData\Local\Programs\Python\Python36\Scripts\audiobook-dl-script.py", line 33, in
> sys.exit(load_entry_point('audiobook-dl==0.1.0', 'console_scripts', 'audiobook-dl')())
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl__main__.py", line 54, in run
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 37, in download
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 51, in combined_audiobook
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\download.py", line 62, in combine_files
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\utils\output.py", line 33, in combine_audiofiles
> File "C:\Users\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
> with Popen(*popenargs, **kwargs) as process:
> TypeError: **init**() got an unexpected keyword argument 'capture_output'

It looks like you are using an older version of python which is missing a feature. I will try to see if I can make it work on older versions.

> is downloading simultaneous since there are thousands of file??any way to work it fast?? I mean it only uses 500KB/s of network speed for me.

I will see what I can do but I don't know much about network speeds. It could also be Scribd limiting the speed.

**Comment by thedkm** [comment]
yeah it could be Scribe throttling but you try to improve it by simultaneous download or something . I will try with latest python

**Comment by thedkm** [comment]
Best match: pycrypto 2.6.1
Processing pycrypto-2.6.1.tar.gz
Writing C:\Users\DKM\AppData\Local\Temp\easy_install-syh8puol\pycrypto-2.6.1\setup.cfg
Running pycrypto-2.6.1\setup.py -q bdist_egg --dist-dir C:\Users\DKM\AppData\Local\Temp\easy_install-syh8puol\pycrypto-2.6.1\egg-dist-tmp-841gaxby
error: Setup script exited with error: SandboxViolation: open('C:\\Users\\DKM\\AppData\\Local\\Programs\\Python\\Python310\\lib\\lib2to3\\Grammar3.10.1.final.0.pickle', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.


Using latest python , now it doesn't even start. Which python do u use?

**Comment by jo1gi** [comment]
I'm using python 3.9. I'm not sure what's wrong. I will see what I can do.

**Comment by thedkm** [comment]
3.9 ohhh and did combine works with aac files and mp3 too?  If yes then I will try again , cus merging aac files which are in thousands is really pain.

**Comment by thedkm** [comment]
BTW some of Scribd Original still doesn't work like these https://www.scribd.com/audiobook/526718263/Nothing and https://www.scribd.com/audiobook/531891826/Self-Help-for-the-Helpless-A-Beginner-s-Guide-to-Personal-Development-Understanding-Self-care-and-Becoming-Your-Authentic-Self

**Comment by jo1gi** [comment]
> BTW some of Scribd Original still doesn't work like these https://www.scribd.com/audiobook/526718263/Nothing and https://www.scribd.com/audiobook/531891826/Self-Help-for-the-Helpless-A-Beginner-s-Guide-to-Personal-Development-Understanding-Self-care-and-Becoming-Your-Authentic-Self

I had no problems downloading them.

> 3.9 ohhh and did combine works with aac files and mp3 too? If yes then I will try again , cus merging aac files which are in thousands is really pain.

I am still working on merging files.

**Comment by thedkm** [comment]
> I am still working on merging files.
ohh , I thought merging was working for you , anyway i hope u can get it working it, merging is really needed here.


> I had no problems downloading them.

    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\audiobook_dl-0.1.0-py3.6.egg\audiobookdl\utils\downloadthread.py", line 21, in
run
    with open(self.path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Self-Help for the Helpless A Beginneru0026#39;s Guide to Personal Development, Understanding
Self-care, and Becoming Your Authentic Self\\Self-Help for the Helpless A Beginneru0026#39;s Guide to Personal Development, Understanding Self-care, and
Becoming Your Authentic Self - Part 19.aac'

**Comment by thedkm** [comment]
merging normal audiobook with 's in name giving me errors 

[concat @ 000002bf650df0c0] Impossible to open 'In Every Mirror She’s Black\In Every Mirror She�s Black - Part 000.mp3'
In Every Mirror She’s Black\combine.txt: No such file or directory
[ERROR] Could not combine audio files

https://www.scribd.com/audiobook/541206296/In-Every-Mirror-She-s-Black-A-Novel

**Comment by jo1gi** [comment]
I think I have fixed the problem. In "Every Mirror She’s Black" is not available in my country so I haven't been able to test it.

**Comment by thedkm** [comment]
[concat @ 0000027a639af0c0] Impossible to open 'Stacey’s Extraordinary Words\Stacey�s Extraordinary Words - Part 000.mp3'
Stacey’s Extraordinary Words\combine.txt: No such file or directory
[ERROR] Could not combine audio files

https://www.scribd.com/audiobook/524097986/Stacey-s-Extraordinary-Words 

test with any available title having 's in name

**Comment by jo1gi** [comment]
I think I have fixed it again. I can't reproduce it. Maybe it's a windows problem?

**Comment by thedkm** [comment]
thanks worked

**Comment by thedkm** [comment]
Is it possibe to have final file name as "author - title" instead of just title after merging ??

**Comment by jo1gi** [comment]
Yes. Just add `-o "{author} - {title}"` to the command.

**Comment by thedkm** [comment]
merging errors for certain special characters still for eg '#' 

https://www.scribd.com/audiobook/530275144/Murder-on-the-Safari-Star-Adventures-on-Trains-3  

  libpostproc    56.  3.100 / 56.  3.100
[concat @ 000002340867cfc0] Impossible to open 'Murder on the Safari Star Adventures on Trains #3 - Part 000.mp3'
M. G. Leonard; Sam Sedgman - Murder on the Safari Star Adventures on Trains #3\combine.txt: No such file or directory
[ERROR] Could not combine audio files

**Comment by jo1gi** [comment]
I have changed how files are combined now. This error shouldn't be a problem anymore.

**Comment by thedkm** [comment]
The 'pycrypto' distribution was not found and is required by audiobook-dl 

this always bothered me I was never able to installed pycrypto' so I used  pycryptodome which was working fine until this new update ,
I have pycrptodome still its not working even tho I reverted files and now i cant make it work :(

**Comment by jo1gi** [comment]
It shouldn't have changed anything about pycrypto. Which error do you get and on which book?

**Comment by thedkm** [comment]
any book I guess can u use pycryptodome instead ??

https://stackoverflow.com/questions/50080459/failed-installing-pycrypto-with-pip

**Comment by jo1gi** [comment]
There isn't any meaningfull differences between pycrypto and pycryptodome, so it doesn't matter.

**Comment by thedkm** [comment]
still its not working for me sadly it was working before :(

**Comment by jo1gi** [comment]
I'm confused by why it's not working. I haven't changed anything to do with pycrypto. The only thing I changed was how files are combined and converted.

**Comment by thedkm** [comment]
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
even after installing build tools same error , I just cant make it work while it was working fine before idk what happened but i cant use it anymore :( 

is any way to use some other crypto then pycrpto?

**Comment by jo1gi** [comment]
I have done it now.

**Comment by thedkm** [comment]
> I have done it now.

wow thank you so much BTW since u changed the combing files method can we have option to show combing progress on output??

**Comment by thedkm** [comment]
Just tested combing files isnt working correctly its producing a file which is just 3 mb

https://www.scribd.com/audiobook/361178128/Warriors-3-Forest-of-Secrets

**Comment by jo1gi** [comment]
Fixed it
