### ISSUE TITLE
i can't use the code 

### ISSUE THREAD

**Issue by yosefomar** [jo1gi/audiobook-dl#81]
**Installation method:**
pip

**Version:**
*Python version : 3.12 and audiobook-dl version: 0.7.2*

**Describe the bug**
C:\Users\Yosef>pip install audiobook-dl
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: audiobook-dl in c:\users\yosef\appdata\roaming\python\python312\site-packages (0.7.2)
Requirement already satisfied: appdirs in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (1.4.4)
Requirement already satisfied: attrs in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (23.2.0)
Requirement already satisfied: cssselect in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (1.2.0)
Requirement already satisfied: importlib-resources in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (6.1.1)
Requirement already satisfied: lxml in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (5.0.0)
Requirement already satisfied: m3u8 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (4.0.0)
Requirement already satisfied: mutagen in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (1.47.0)
Requirement already satisfied: pillow in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (9.5.0)
Requirement already satisfied: pycryptodome in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (3.19.1)
Requirement already satisfied: requests in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (2.31.0)
Requirement already satisfied: rich in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (13.7.0)
Requirement already satisfied: tomli in c:\users\yosef\appdata\roaming\python\python312\site-packages (from audiobook-dl) (2.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from requests->audiobook-dl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from requests->audiobook-dl) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from requests->audiobook-dl) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from requests->audiobook-dl) (2023.11.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from rich->audiobook-dl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from rich->audiobook-dl) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\yosef\appdata\roaming\python\python312\site-packages (from markdown-it-py>=2.2.0->rich->audiobook-dl) (0.1.2)

C:\Users\Yosef>audiobook-dl
'audiobook-dl' is not recognized as an internal or external command,
operable program or batch file.

audiobook-dl -d --username email@gmail.com --password pass --combine --output-format mp3 --output /Audiobooks/{author}/{series}/{title}/ https://www.storytel.com/eg/ar/books/homo-deus-a-brief-history-of-tomorrow-115032
'audiobook-dl' is not recognized as an internal or external command,
operable program or batch file.

**Comment by freddy36** [comment]
not a bug, make sure your script path is added to the PATH environment variable:
in your case it's probably installed to `c:\users\yosef\appdata\roaming\python\python312\Scripts\audiobook-dl.exe`

**Comment by yosefomar** [comment]
i added to the PATH environment variable
![Screenshot 2024-01-02 150027](https://github.com/jo1gi/audiobook-dl/assets/75320068/d06c763f-fe82-48b5-b7de-fe32fbb0d0fd)
but it works when i write c:\users\yosef\appdata\roaming\python\python312\Scripts\audiobook-dl.exe then the command

**Comment by freddy36** [comment]
You have to add just the path of the Scripts directory, not the complete path to the exe file
