### ISSUE TITLE
Only got a 2 minute clip

### ISSUE THREAD

**Issue by OABiblicalHebrew** [jo1gi/audiobook-dl#90]
**Installation method:**
 pip

**Version:**
audiobook-dl 0.7.3
Python 3.10.12

**Describe the bug**
Don't know if this is a user error but I only got a 2 minute clip when I downloaded a book using the following command. Is there a different url I should be providing? 
audiobook-dl --username "<user>" --password "<pass>" "https://www.storytel.com/il/he/books/%D7%94%D7%91%D7%A0%D7%99%D7%99%D7%9F-%D7%94%D7%A8%D7%99%D7%A7-2574298"

**Comment by jo1gi** [comment]
There is a new version of the Storytel code that hopefully fixes it (https://github.com/jo1gi/audiobook-dl/pull/84).

**Comment by OABiblicalHebrew** [comment]
ok how would I use the new Storytel code?
